config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :posts do
    member do
      post :like_create
      delete :like_destroy
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "login" =>"users#login_form"
  post "login" =>"users#login"
  post "logout" => "users#logout"
  root "home#top"
  get "about" => "home#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes

  validates :content, presence: true, length: { in: 1..140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, length: { in: 1..15 }
  validates :email, presence: true, length: { maximum: 100 }
  validates :desc, presence: true, length: { in: 1..140 }

  has_many :posts
  has_many :likes
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :nickname, :desc, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like_create, :like_destroy]
  before_action :set_like, only: :like_destroy

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '投稿を作成しました' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '投稿を編集しました' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '投稿を削除しました' }
      format.json { head :no_content }
    end
  end

  def like_create
    Like.create!(user: current_user, post: @post) if @post
    redirect_to posts_path
  end

  def like_destroy
    @like.destroy
    redirect_to posts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :content)
    end

    def set_like
      @like = Like.find_by(user: current_user, post: @post)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to @user
    end
  end

  private
  def set_user
     @user = User.find(params[:follow_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:nickname, :email, :desc)
    end
    def login_form
    end
    def login
      @user = User.find_by(email:params[:email],password:params[:password])
      if @user
        session[:user_id]= @user.id
        flash[:notice] = "ログインしました"
        redirect_to("/posts/index")
      else
        @error_messages="メールアドレスまたはパスワードが間違っています"
        @email= params[:email]
        @password= params[:password]

        render("users/login_form")

    end
    def logout
      session[:user_id]=nil
      flash[:notice]="ログアウトしました"
      redirect_to("/login")
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="about-main">
  <h2>Twitterとは</h2>
  <p>
    今すぐ話せるユーザーがたくさん！！
    ツイート機能で暇な相手に話しかけよう
  </p>
  <img class="about-img" src="/follow-button1.jpg">
  </div>

app/views/home/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>国内最大級でつながれるコミュニティ</h2>
    <p>今の気持ちをつぶやいてみよう！</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <meta content="width=1440, maximum-scale=1.0" name="viewport"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-logo">
        <%=link_to "Twitter-Sample", root_path %>
      </div>
      <ul class="header-menus">
        <li>
          <%= link_to "Twitterとは", about_path %>
        </li>

        <% if current_user %>
          <li>
            <%= link_to "投稿一覧", posts_path %>
          </li>
          <li>
            <%= link_to "ユーザ一覧", users_path %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "ログイン", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </header>

    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content,id: "input-text" %>
    <p id="counter">0文字</p>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="wrapper">
  <p id="notice"><%= notice %></p>

  <% @posts.reverse.each do |post| %>
    <div class="post-wrapper">
      <%= link_to post do %>
        <div class="card">
          <%= image_tag 'https://source.unsplash.com/random/?people' %>
          <div class="content-wrapper">
            <div class="name">
              <%= post.user.nickname %>
            </div>
            <div class="content">
              <%= post.content %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="del-btn">
        <% if current_user.likes.map{|x| x.post }.include?(post) %>
          <%= link_to like_destroy_post_path(post), method: :delete do %>
            <i class="fa fa-heart" aria-hidden="true"></i>
          <% end %>
        <% else %>
          <%= link_to like_create_post_path(post), method: :post do %>
            <i class="fa fa-heart-o" aria-hidden="true"></i>
          <% end %>
        <% end %>
        <%= post.created_at.strftime('%Y年%m月%d日 %H:%M') %>
        <%= link_to '削除', post, method: :delete, data: { confirm: '削除してもよろしいですか?' } %>
      </div>

    </div>
  <% end %>

  <br>

  <%= link_to '新規投稿', new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="wrapper">
  <h1>新規投稿</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>user:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="wrapper">
  <p id="notice"><%= notice %></p>

  <h1>ユーザー一覧</h1>

  <table>
    <thead>
      <tr>
        <th>ニックネーム</th>
        <th>メール</th>
        <th>自己紹介</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.nickname %></td>
          <td><%= user.email %></td>
          <td><%= user.desc %></td>
          <td><%= link_to 'プロフィール', user %></td>
          <td><%= link_to '編集', edit_user_path(user) %></td>
          <td><%= link_to '削除', user, method: :delete, data: { confirm: 'アカウントを削除してもよろしいでしょうか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
        <%= form_tag("/login") do %>
          <p>メールアドレス</p>
          <input type="email" name ="email" value="<%= @email %>">
          <p>パスワード</p>
          <input type="password" name="password" value="<%= @password%>">
          <input type="submit" value="ログイン">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @user.desc %>
</p>

<%= render 'relationships/follow_button', user: @user %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>